windows:
	GOOS='windows' GOARCH='amd64' go build main.go
mac:
	GOOS='darwin' GOARCH='386' go build main.go
linux:
	GOOS='linux' GOARCH='amd64' go build main.go
arm:
	GOOS='linux' GOARCH='arm64' go build main.go
